### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by ibrahimkteish** [Saik0s/TCAStarter#1]
After running "make" as mentioned in the readme, I encountered the following error:
// omitted output
Loading and constructing the graph
It might take a while if the cache is empty
Couldn't find xcframework at /Users/omitted/SkeletonProject/SkeletonProject/Support/RevealServer.xcframework
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [project_file] Error 1

**Comment by Saik0s** [comment]
Hey @ibrahimkteish , thanks for reporting, should be fixed now.
